export const projects = [
  {
    id: "1",
    title: "Eksempelprosjekt 1",
    image: "/prosjektBilde1.jpg",
    description: "Transformasjon av stue og kjøkken.",
    city: "Oslo",
    service: "Boligstyling",
  },
  {
    id: "2",
    title: "Eksempelprosjekt 2",
    image: "/prosjektBilde2.jpg",
    description: "Utleiestyling for salg.",
    city: "Bergen",
    service: "Utleiestyling",
  },
  {
    id: "3",
    title: "Eksempelprosjekt 3",
    image: "/prosjektBilde3.jpg",
    description: "Konsultasjon og fargeråd.",
    service: "Konsultasjon",
  },
  {
    id: "4",
    title: "Eksempelprosjekt 4",
    image: "/prosjektBilde5.jpg",
    description: "Konsultasjon og fargeråd.",
    service: "Konsultasjon",
  },
  {
    id: "5",
    title: "Eksempelprosjekt 5",
    image: "/prosjektBilde4.jpg",
    description: "Konsultasjon og fargeråd.",
    service: "Konsultasjon",
  },
  {
    id: "6",
    title: "Eksempelprosjekt 6",
    image: "/prosjektBilde6.jpg",
    description: "Konsultasjon og fargeråd.",
    service: "Konsultasjon",
  },
];
